// Expo config plugin (Seeker flavor only): resolve *.polymarket.com over DNS-over-HTTPS.
//
// Why: some ISPs (seen 2026-10-04 on AS35362 Best ISP, UA) answer clob/relayer-v2.polymarket.com with
// a block stub (10.125.0.2) from their resolver, so a real order dies in the TLS handshake ("Unable to
// parse TLS packet header") even though Polymarket itself serves the user's IP (/api/geoblock says
// blocked:false). Real orders are posted from the phone (the server's region is geoblocked by
// Polymarket), so the phone has to resolve Polymarket correctly. Owner decision, 2026-10-04.
//
// What it does at prebuild:
//   1. app/build.gradle  — adds okhttp-dnsoverhttps at the SAME version as the okhttp React Native
//      resolves (4.9.2 for RN 0.86 — check `gradlew :app:dependencyInsight --dependency okhttp`
//      after an RN upgrade; a mismatch fails at runtime with NoSuchMethodError).
//   2. PolymarketDoh.kt  — an OkHttpClientFactory: RN's default client (cache + cookie jar) with a Dns
//      that sends *.polymarket.com to Cloudflare DoH (then Google DoH), by IP, so the ISP resolver is
//      never asked. Every other host keeps the system resolver. If both DoH lookups fail, it falls
//      back to the system resolver — i.e. exactly today's behaviour, never worse.
//   3. MainApplication.kt — registers the factory before React Native loads, so every fetch / XHR
//      (the Polymarket SDK included) uses it. TLS is untouched: certificates are verified as usual.
/* eslint-disable @typescript-eslint/no-require-imports -- Expo config plugins are CommonJS by design */
const fs = require("fs");
const path = require("path");
const { withAppBuildGradle, withDangerousMod, withMainApplication } = require("expo/config-plugins");

const DOH_DEP = 'implementation("com.squareup.okhttp3:okhttp-dnsoverhttps:4.9.2")';
const REGISTER = "com.facebook.react.modules.network.OkHttpClientProvider.setOkHttpClientFactory(PolymarketDohClientFactory(this))";

// `fun` is a Kotlin keyword, so the package segment has to be back-quoted in source.
const kotlinPackage = (pkg) => pkg.split(".").map((s) => (s === "fun" ? "`fun`" : s)).join(".");

const kotlinSource = (pkg) => `package ${kotlinPackage(pkg)}

import android.content.Context
import com.facebook.react.modules.network.OkHttpClientFactory
import com.facebook.react.modules.network.OkHttpClientProvider
import java.net.InetAddress
import java.net.UnknownHostException
import okhttp3.Dns
import okhttp3.HttpUrl.Companion.toHttpUrl
import okhttp3.OkHttpClient
import okhttp3.dnsoverhttps.DnsOverHttps

// Generated by mobile/plugins/withPolymarketDoh.js — edit the plugin, not this file.
// *.polymarket.com resolves over DoH (Cloudflare, then Google), reached by IP so the ISP resolver is
// never involved; everything else uses the system resolver. Both DoH lookups failing falls back to
// the system resolver, so this can only ever add reachability.
class PolymarketDns(bootstrap: OkHttpClient) : Dns {
  private val resolvers: List<DnsOverHttps> = listOf(
    DnsOverHttps.Builder().client(bootstrap)
      .url("https://cloudflare-dns.com/dns-query".toHttpUrl())
      .bootstrapDnsHosts(InetAddress.getByName("1.1.1.1"), InetAddress.getByName("1.0.0.1"))
      .build(),
    DnsOverHttps.Builder().client(bootstrap)
      .url("https://dns.google/dns-query".toHttpUrl())
      .bootstrapDnsHosts(InetAddress.getByName("8.8.8.8"), InetAddress.getByName("8.8.4.4"))
      .build(),
  )

  override fun lookup(hostname: String): List<InetAddress> {
    if (hostname == "polymarket.com" || hostname.endsWith(".polymarket.com")) {
      for (resolver in resolvers) {
        try {
          val found = resolver.lookup(hostname)
          if (found.isNotEmpty()) return found
        } catch (e: UnknownHostException) {
          // try the next resolver, then the system one
        }
      }
    }
    return Dns.SYSTEM.lookup(hostname)
  }
}

class PolymarketDohClientFactory(private val context: Context) : OkHttpClientFactory {
  override fun createNewNetworkModuleClient(): OkHttpClient {
    val bootstrap = OkHttpClient.Builder().build()
    return OkHttpClientProvider.createClientBuilder(context).dns(PolymarketDns(bootstrap)).build()
  }
}
`;

const withPolymarketDoh = (config) => {
  const pkg = config.android?.package;
  if (!pkg) throw new Error("withPolymarketDoh: android.package is not set");

  config = withAppBuildGradle(config, (cfg) => {
    if (!cfg.modResults.contents.includes("okhttp-dnsoverhttps")) {
      cfg.modResults.contents = cfg.modResults.contents.replace(
        /dependencies\s*\{/,
        (m) => `${m}\n    // withPolymarketDoh: must match the okhttp version React Native resolves.\n    ${DOH_DEP}`,
      );
    }
    return cfg;
  });

  config = withMainApplication(config, (cfg) => {
    let src = cfg.modResults.contents;
    if (!src.includes("PolymarketDohClientFactory")) {
      if (!src.includes("loadReactNative(this)")) throw new Error("withPolymarketDoh: loadReactNative(this) not found in MainApplication");
      src = src.replace(/(\n\s*)loadReactNative\(this\)/, `$1${REGISTER}$1loadReactNative(this)`);
    }
    cfg.modResults.contents = src;
    return cfg;
  });

  return withDangerousMod(config, [
    "android",
    (cfg) => {
      const dir = path.join(cfg.modRequest.platformProjectRoot, "app", "src", "main", "java", ...pkg.split("."));
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(path.join(dir, "PolymarketDoh.kt"), kotlinSource(pkg));
      return cfg;
    },
  ]);
};

module.exports = withPolymarketDoh;
